spring.application.name=search-service
server.port=8080

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=
spring.elasticsearch.password=

logging.level.com.example.search=INFO
