spring.datasource.url=jdbc:mysql://localhost:3306/spring_batch_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.batch.job.enabled=true
